spring:
  datasource:
    url: jdbc:postgresql://localhost/decoder_acars
    username: decoder_acars
    password: 123456
  jpa:
    database: postgresql
    show-sql: false
    hibernate.ddl-auto: none
